### ISSUE TITLE
[🐞Bug]  [🛑Blocker]  Recursive Bug exceeding and crashing callstack

### ISSUE THREAD

**Issue by DevonGifford** [mutaremalcolm/capstone1#21]
# Recursive Bug exceeding and crashing call stack #20 

## The Problem

_User faces an error when trying to register a new account - website crashes._

**Crash Error:**
user creation encountered an error range Error maximum call stack size exceeded at `createASuthUserWIthEmailAndPassword`
(firebase.utils.jsx:74:1)

![image](https://github.com/mutaremalcolm/capstone1/assets/118319299/086be81a-05da-49fa-907e-30893926f511)

<hr>

## The Solution 

Based of the [latest commit](https://github.com/mutaremalcolm/capstone1/pull/20)

In `src/utils/firebase/firebase.utils.jsx`   [specifically this file](https://github.com/mutaremalcolm/capstone1/blob/main/src/utils/firebase/firebase.utils.jsx)

Specifically at the `createAuthUserWithEmailAndPassword` function

Error found in return statement 

###  **current implementation**
```jsx
  export const createAuthUserWithEmailAndPassword = async (email, password) => {  // <-- note the same name - error
    if (!email || !password) return;

      return await createAuthUserWithEmailAndPassword(auth, email, password)   // <-- note the same name - error
  };
```

###  **suggested implementation**
```jsx
  export const createAuthUserWithEmailAndPassword = async (email, password) => {
    if (!email || !password) return;

      return await createUserWithEmailAndPassword(auth, email, password);  // note the changes made here    
  };
```

**Comment by mutaremalcolm** [comment]
Solution was implemented succesfully. Bug detected and removed. Thank you

**Comment by mutaremalcolm** [comment]
Issue is now resolved and closed.
